### PR TITLE
upgrade libnanomsg to version 1.0.0

### PR DESCRIPTION
**Pull request by hamidreza-s**

### CODE REVIEW

**Comment by vinoski** [comment]
When I compile and run this on macOS 10.12.6 under Erlang/OTP 20.0, everything builds OK but testing fails:

```
======================== EUnit ========================
module 'enm_survey'
  enm_survey: surveyor_test_...[0.001 s] ok
  [done in 0.004 s]
module 'enm_sup'
enm_start_stop: start_stop_test (module 'enm_start_stop')...0   enm_drv.so                          0x000000001bf19768 nn_mutex_lock + 56
1   enm_drv.so                          0x000000001bf0915d nn_term + 29
2   enm_drv.so                          0x000000001bf01d61 enm_control + 1345
3   beam.smp                            0x0000000016ecc956 call_driver_control + 278
Invalid argument [22] (/usr/local/src/enm/c_src/nanomsg-1.0.0/src/utils/mutex.c:89)
Abort trap: 6
```

But on the master branch, all tests pass.

**Comment by hamidreza-s** [comment]
I had compiled and tested it successfully on an Ubuntu 14.04.5 LTS machine under Erlang/OTP 20 [erts-9.0] with no error. 

But you are totally right, I just compiled and tested it again this time on macOS 10.11.3 under Erlang/OTP 18 [erts-7.2.1] and got the following error which is similar to what you got:
```
======================== EUnit ========================
module 'enm_survey'
  enm_survey: surveyor_test_...[0.005 s] ok
  [done in 0.008 s]
module 'enm_sup'
enm_start_stop: start_stop_test (module 'enm_start_stop')...0   enm_drv.so                          0x000000000c419afe nn_mutex_lock + 62
1   enm_drv.so                          0x000000000c408f4d nn_term + 29
2   enm_drv.so                          0x000000000c40253e enm_control + 1390
3   beam.smp                            0x0000000009a0b877 erts_port_control + 871
4   beam.smp                            0x0000000009a847e7 erts_internal_port_control_3 + 210
5   beam.smp                            0x000000000999b4e4 process_main + 32570
6   beam.smp                            0x0000000009a1d771 sched_thread_func + 501
7   beam.smp                            0x0000000009b1d124 thr_wrapper + 144
8   libsystem_pthread.dylib             0x00007fff98da0c13 _pthread_body + 131
9   libsystem_pthread.dylib             0x00007fff98da0b90 _pthread_body + 0
10  libsystem_pthread.dylib             0x00007fff98d9e375 thread_start + 13
Invalid argument [22] (/Users/hamidreza/Code/Them/enm/c_src/nanomsg-1.0.0/src/utils/mutex.c:89)
make: *** [test] Abort trap: 6
```
It seems that [here](https://github.com/nanomsg/nanomsg/blob/master/src/utils/mutex.c#L84-L90) after calling `nn_mutex_lock` function inside `nn_term` causes this error in libnanomsg. So, when I removed `nn_term/0` erlang function from enm [here](https://github.com/basho/enm/blob/master/src/enm.erl#L381) before unloading the driver, the tests passed.

I couldn't find the root cause of this error in libnanomsg, but it seems that `nn_term` function in libnanomsg is buggy and has [4 open issues](https://github.com/nanomsg/nanomsg/issues?q=nn_term+is%3Aopen) at the time of writing. Even, in one of the issues the maintener of the library says he'd avoid using nn_term actually ([conversation thread](https://github.com/nanomsg/nanomsg/issues/854#issuecomment-266382963)).

So, if you agree I can remove `nn_term/0` before unloading the driver to pass the tests.

**Comment by vinoski** [comment]
I think not calling `nn_term` is a good approach. Can you use the patch below please?

```
diff --git a/c_src/enm_drv.c b/c_src/enm_drv.c
index b4f5dbe..493bc96 100644
--- a/c_src/enm_drv.c
+++ b/c_src/enm_drv.c
@@ -603,7 +603,10 @@ enm_control(ErlDrvData drv_data, unsigned int command,
         break;

     case ENM_TERM:
-        nn_term();
+        /* Ideally here we should call nn_term() but it has problems, as
+           discussed at the github nanomsg repository in issues such as
+           #854 (https://github.com/nanomsg/nanomsg/issues/854), so this is
+           a no-op instead. */
         break;

     case ENM_GETOPTS:
```

**Comment by vinoski** [comment]
Unfortunately even with the new patch I still see similar failures:

```
======================== EUnit ========================
module 'enm_survey'
  enm_survey: surveyor_test_...[0.002 s] ok
  [done in 0.005 s]
module 'enm_sup'
enm_start_stop: start_stop_test (module 'enm_start_stop')...
0   enm_drv.so                          0x00000000214d9778 nn_mutex_lock + 56
1   enm_drv.so                          0x00000000214c9250 nn_close + 32
2   enm_drv.so                          0x00000000214c0f34 enm_stop + 500
3   beam.smp                            0x000000001e503ae7 terminate_port + 167
Invalid argument [22] (/usr/local/src/enm/c_src/nanomsg-1.0.0/src/utils/mutex.c:89)
Abort trap: 6
```

**Comment by hamidreza-s** [comment]
What I had done at first to get the test passed was not calling `nn_term/0` from Erlang source side as follows:

```
diff --git a/src/enm.erl b/src/enm.erl
index 00b7d30..db9c396 100644
--- a/src/enm.erl
+++ b/src/enm.erl
@@ -378,7 +378,6 @@ handle_call(_Request, _From, State) ->
     {reply, ok, State}.
 
 handle_cast(stop, State) ->
-    ok = nn_term(),
     case erl_ddll:try_unload(?SHLIB, [{monitor, pending_driver}]) of
         {ok, unloaded} ->
             {stop, normal, State};
@@ -616,10 +615,6 @@ wait_for_stop() ->
             wait_for_stop()
     end.
 
-nn_term() ->
-    Port = erlang:open_port({spawn_driver, ?SHLIB}, [binary]),
-    binary_to_term(port_control(Port, ?ENM_TERM, <<>>)).
-
 transfer_unreceived_msgs(Sock, Type, Owner) ->
     receive
         {Type, Sock, _}=Msg ->
```

So, based on your last bug report, opening a port and performing a synchronous control operation by calling `nn_term/0` in Erlang source side causes the problem even if in C driver source side we don't take `NN_TERM` control into effect.

My other finding is that, this mutex problem in libnanomsg happens when we stop the driver right after starting it without any actions such as opening socket and sending message. This situation is exactly what we test in `enm_start_stop.erl` test case.

Since it is a MacOS specific error, I tried to find the root cause with debugging the driver by LLDB which is not well supported in [cerl](https://github.com/erlang/otp/blob/master/erts/etc/unix/cerl.src) for debugging run-time. So, because of the poor support of LLDB and some troubles to get GDB working in MacOS, I couldn't find the root cause.

Finally, if removing the `nn_term/0` functionality from Erlang source side is not a crazy solution for now to have the latest version of libnanomsg, I can create another PR to upgrade the library, build process, and replace `nn_term/0` with a comment describing the reason of its removal in one commit.

**Comment by vinoski** [comment]
Your suggestion sounds reasonable, though the approach I would take would be to apply the patch below, then squash the commits in this branch down to a single commit.

```
diff --git a/src/enm.erl b/src/enm.erl
index 00b7d30..ffeb9b7 100644
--- a/src/enm.erl
+++ b/src/enm.erl
@@ -617,8 +617,11 @@ wait_for_stop() ->
     end.

 nn_term() ->
-    Port = erlang:open_port({spawn_driver, ?SHLIB}, [binary]),
-    binary_to_term(port_control(Port, ?ENM_TERM, <<>>)).
+    %% Ideally here we should call nn_term() in the driver but it has
+    %% problems, as discussed at the github nanomsg repository in issues
+    %% such as #854 (https://github.com/nanomsg/nanomsg/issues/854), so
+    %% this is a no-op instead.
+    ok.

 transfer_unreceived_msgs(Sock, Type, Owner) ->
     receive
```

**Comment by vinoski** [comment]
I manually squashed the commits to one, and then rebased to master. Thanks!

**Pull request closed without merging**
