### PR TITLE
update rebar to rebar3

### PR DESCRIPTION
**Pull request by Elzor**
Rebar is deprecated that's why I have improved building process with rebar3.

### CODE REVIEW

**Comment by vinoski** [comment]
Thanks for this contribution.

I thing I don't like, though, is the `make` support for fetching a `rebar3` executable. Given that `rebar3` is a build tool that's used for many projects and is completely independent of `enm`, it should be up to the user to manage it separately. I'd prefer to see a check for `rebar3` in the `PATH` and if not found, issue an informative error message telling the user where to get it.

**Comment by Elzor** [comment]
Ok, I've improved this.
I thought enm is a library and it's included into other projects with their top level rebar3. Actually when we build project via rebar it doesn't execute make command at all and enm's rebar3 can't be downloaded.

**Comment by vinoski** [comment]
OK, thanks.

Yes, `enm` is a library, and what you say about how it's built for projects that use it is true. However, `enm` is also a development project that has had a number of contributors &mdash; you, for example &mdash; and for all contributors, I'd prefer that we manage `rebar3` correctly within the project.

**Comment by vinoski** [comment]
Rebased to master. Thanks Maxim!

**Pull request closed without merging**
